const Sequelize = require('sequelize');
module.exports = function(sequelize, DataTypes) {
  return sequelize.define('UrlRewrite', {
    url_rewrite_id: {
      autoIncrement: true,
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      primaryKey: true,
      comment: "Rewrite ID"
    },
    entity_type: {
      type: DataTypes.STRING(32),
      allowNull: false,
      comment: "Entity type code"
    },
    entity_id: {
      type: DataTypes.INTEGER.UNSIGNED,
      allowNull: false,
      comment: "Entity ID"
    },
    request_path: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: "Request Path"
    },
    target_path: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: "Target Path"
    },
    redirect_type: {
      type: DataTypes.SMALLINT.UNSIGNED,
      allowNull: false,
      defaultValue: 0,
      comment: "Redirect Type"
    },
    store_id: {
      type: DataTypes.SMALLINT.UNSIGNED,
      allowNull: false,
      comment: "Store ID"
    },
    description: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: "Description"
    },
    is_autogenerated: {
      type: DataTypes.SMALLINT.UNSIGNED,
      allowNull: false,
      defaultValue: 0,
      comment: "Is rewrite generated automatically flag"
    },
    metadata: {
      type: DataTypes.STRING(255),
      allowNull: true,
      comment: "Meta data for url rewrite"
    }
  }, {
    sequelize,
    tableName: 'url_rewrite',
    timestamps: false,
    indexes: [
      {
        name: "PRIMARY",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "url_rewrite_id" },
        ]
      },
      {
        name: "URL_REWRITE_REQUEST_PATH_STORE_ID",
        unique: true,
        using: "BTREE",
        fields: [
          { name: "request_path" },
          { name: "store_id" },
        ]
      },
      {
        name: "URL_REWRITE_TARGET_PATH",
        using: "BTREE",
        fields: [
          { name: "target_path" },
        ]
      },
      {
        name: "URL_REWRITE_STORE_ID_ENTITY_ID",
        using: "BTREE",
        fields: [
          { name: "store_id" },
          { name: "entity_id" },
        ]
      },
      {
        name: "URL_REWRITE_ENTITY_ID",
        using: "BTREE",
        fields: [
          { name: "entity_id" },
        ]
      },
    ]
  });
};
